import re
import pandas as pd

def split_into_sentences_with_prompts(text, n):
    sentences = re.split("(?<=[.!?]) +", text)
    prompts = sentences[::n]
    completions = []
    for i in range(len(prompts) - 1):
        completion = " ".join(sentences[n*i+1:n*(i+1)])
        completions.append(completion)
    completions.append(" ".join(sentences[n*(len(prompts)-1)+1:]))
    data = {'prompt': prompts, 'completion': completions}
    df = pd.DataFrame(data)
    return df

text = "There are two relevant data trends. Data is expected to grow from 33 ZB (zettabytes) today to 175 ZB in 5 years . And the cloud 2"\
+"is moving to the edge for performance and availability, driven by IoT applications, multi-player gaming, autonomous vehicles,"\
+"and content streaming. Decentralization would accelerate this change and adoption, as it lowers deployment, management, and"\
+"scale-out cost. To this end, 0Chain is decentralizing storage."\
+"0Chain dStorage is cheaper and higher performance than traditional cloud. The protocols provide a layer of privacy, security,"\
+"transparency, and service assurance. For consumers, the benefits are privacy, anonymity, and transparency. Developers have"\
+"better customer data protection at a lower cost. Enterprises can scale out their data protection at a lower cost. For MSPs, dStorage"\
+"provides a higher revenue potential."\
+"The dStorage platform is built on 0ChainNet, a permission-less, fast finality, scalable blockchain, built from scratch in Golang."\
+"0ChainNet protects its network from Sybil with a Nonlinear Proof-of-Stake protocol, and prevents blockchain stalls from DDoS"\
+"attacks by using multiple leaders. Client protection is accomplished by using a Serverless 2FA protocol for individuals, and a"\
+"cryptographic multiple signature protocol for exchanges and businesses."\
+"0ChainNet offers innovative token economics which enables users and developers to get “free” services, such as transactions and"\
+"storage. Users can lock ZCN tokens , like a bank CD, to get interest tokens immediately. Storage providers (“blobbers”) need to 3"\
+"stake ZCN tokens to receive expected payment. As more applications use our network, ZCN will grow in its intrinsic value"\
+"relative to the data stored on the network, and tokens locked for interest, as users interactively lock and stake tokens to participate"\
+"in the ecosystem. In this sense, ZCN is the first crypto asset tied to data and interest."\
+"Unlike Bitcoin, Ethereum, and other projects, 0Chain inflation is primarily driven by token holders desire to mint “interest”"\
+"tokens, which are given to token holders for locking or staking their tokens, rather than “reward” tokens given to miners only."\
+"0Chain has recently re-tooled its token economics to provide on-going rewards to support the community of developers and"\
+"ambassadors as well. In addition, 0Chain has allocated a portion of team tokens to fund the reward tokens for the first 4 years"\
+"after mainnet to maintain low inflation. After 4 years, the rewards will be generated by the network and the interest will be set at"\
+"5% to maintain an average target inflation rate of about 3-4%. This provides benefits to the entire ecosystem - miners, developers,"\
+"ambassadors, and token holders at a low inflation rate."\
+"1 dStorage Platform"\
+"The motivation behind the design of the platform is to offer a cheaper, faster, more secure and more available storage than"\
+"traditional cloud. Let’s discuss some inherent challenges with offering such a service in a decentralized environment."\
+"a) How to protect against data loss?"\
+"b) How to ensure that even if one or some of the decentralized parties are down, the overall service is not effected for every"\
+"single stored file or object?"\
+"c) How to make certain that the decentralized parties are really storing the data for which they are getting rewarded?"\
+"d) How to avoid currency fluctuation for our managed storage provider (MSP) customers?"\
+"e) How do dApps preserve data consistency among multiple parties to execute their smart contracts?"\
+"Some challenges are inherent and relatively new to the decentralized systems. Below, we will explore each of these challenges"\
+"and the approach 0Chain dStorage has taken. This has been also discussed in the EthResearch forum . "
n = 5
df = split_into_sentences_with_prompts(text, n)
print(df)

df.to_json('data.jsonl', orient='records', lines=True)


